
on:
  workflow_dispatch:


jobs:
  hello_world_job:

    name: A job to say hello
    continue-on-error: true
    strategy:
      max-parallel: 3
      matrix:
       os: [ubuntu-latest, windows-latest, macOS-latest]


    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: milankomaj/shell-x@v0.1
        with:
          who-to-greet: '${{ github.actor }}'
          neofetch: 'false'
          shell: 'pwsh'
          locale: 'sk_SK'
          timezone: 'Central Europe Standard Time'

      - run: ðŸ’¡ ${{ steps.foo.outputs.random-number }}
        shell: bash

      - run: ðŸ’¡ ${{ steps.foo.outputs.inputs-outputs }}
        shell: bash


      - name: date ${{ matrix.os }}
        if: ${{matrix.os != 'windows-latest'}}
        run: |
            date

      - name: date ${{ matrix.os }}
        if: ${{matrix.os == 'windows-latest'}}
        run: |
         Get-TimeZone
         Get-Date -UFormat "%A %m/%d/%Y %R %Z"
         date