
on:
  workflow_dispatch:


jobs:
  hello_world_job:

    name: A job to say hello
    continue-on-error: true
    strategy:
      max-parallel: 3
      matrix:
       os: [ubuntu-latest, windows-latest, macOS-latest]


    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: milankomaj/shell-x@v0.46
        with:
          shell: 'cmd'

      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash

      - run: echo use-os ${{ matrix.os }}

      - name: date ${{ matrix.os }}
        if: ${{matrix.os != 'windows-latest'}}
        run: |
            date

      - name: date ${{ matrix.os }}
        if: ${{matrix.os == 'windows-latest'}}
        run: |
         Get-TimeZone
         Get-Date -UFormat "%A %m/%d/%Y %R %Z"
         date