name: test
run-name: ${{ github.workflow }} ✅ ${{ github.actor }} ✅ ${{ github.event_name}}
on:
  workflow_dispatch:


jobs:

  Shell:
    name: Shell
    continue-on-error: false
    strategy:
      max-parallel: 3
      matrix:
       os: [windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: Get-Date -Format F
      - id: foo
        uses: milankomaj/shell-x@v0.1
        with:
          who-to-greet: ${{ github.actor }}
          neofetch: false
          shell: pwsh {7}
          locale: sk_SK
          timezone: Central Europe Standard Time
          comand: |
           Get-Date -Format F && Get-Date -UFormat "%Y%m%d"

      - run: echo ${{ steps.foo.outputs.random-number }}
        shell: pwsh

      - run: echo ${{ steps.foo.outputs.inputs-outputs }}
        shell: pwsh

      - run: ${{ steps.foo.outputs.comand-outputs }}
        shell: pwsh

      - run: |
         echo "::debug::Set the Octocat variable"
         echo "::warning file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
         echo ${{ steps.foo.outputs.comand-outputs }}
        shell: pwsh